---
site_name: hxp的文档库
site_url: https://docs.hxp.plus
site_author: 胡喜平
repo_url: https://github.com/hxp-plus/docs.hxp.plus.git
repo_name: docs.hxp.plus
theme:
  name: material
  custom_dir: docs/overrides
  language: zh
  font: false
  palette:
    primary: indigo
  features:
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - navigation.top
    - navigation.footer
    - navigation.prune
    - search.suggest
    - search.highlight
    - search.share
    - header.autohide
    - toc.follow
    - content.code.copy
nav:
  - 首页: index.md
  - 容器技术:
      - Kubernetes:
          - 银河麒麟V10安装Kubernetes: 容器技术/Kubernetes/银河麒麟V10安装Kubernetes.md
          - 对接CephFS存储: 容器技术/Kubernetes/对接CephFS存储.md
          - 安装traefik ingress controller: 容器技术/Kubernetes/安装traefik ingress controller.md
          - 安装helm包管理器: 容器技术/Kubernetes/安装helm包管理器.md
          - 安装metrics-server: 容器技术/Kubernetes/安装metrics-server.md
          - 配置私有镜像仓库凭证: 容器技术/Kubernetes/配置私有镜像仓库凭证.md
          - 禁用容器镜像垃圾回收并配置磁盘相关容器漂移策略: 容器技术/Kubernetes/禁用容器镜像垃圾回收并配置磁盘相关容器漂移策略.md
          - local-path-provisioner安装: 容器技术/Kubernetes/local-path-provisioner安装.md
          - 扩容master节点: 容器技术/Kubernetes/扩容master节点.md
          - k3s删除namespace卡死在Terminating解决方法: 容器技术/Kubernetes/k3s删除namespace卡死在Terminating解决方法.md
          - k8s 开启 swap 支持: 容器技术/Kubernetes/k8s开启swap支持.md
      - Docker&Podman:
          - Dockerfile中不保留编译缓存: 容器技术/Docker&Podman/Dockerfile中不保留编译缓存.md
          - 基于eBPF的容器审计技术的实现: 容器技术/Docker&Podman/基于eBPF的容器审计技术的实现.md
  - 前端开发:
      - Vue3:
          - Geeker-Admin接入Keycloak认证: 前端开发/Vue3/Geeker-Admin接入Keycloak认证.md
  - 存储技术:
      - Ceph:
          - 银河麒麟V10安装Ceph: 存储技术/Ceph/银河麒麟V10安装Ceph.md
      - ZFS:
          - TrueNAS删除所有空快照: 存储技术/ZFS/TrueNAS删除所有空快照.md
  - 运维开发:
      - AWX:
          - AWX和stolon高可用调优: 运维开发/AWX/AWX和stolon高可用调优.md
          - 使用stolon安装高可用PostgreSQL: 运维开发/AWX/使用stolon安装高可用PostgreSQL.md
          - 安装AWX-23.7: 运维开发/AWX/安装AWX-23.7.md
          - AWX-23.9使用SAML对接keycloak认证: 运维开发/AWX/AWX-23.9使用SAML对接keycloak认证.md
          - AWX增加并使用token: 运维开发/AWX/AWX增加并使用token.md
          - AWX设置SAML认证用户为管理员: 运维开发/AWX/AWX设置SAML认证用户为管理员.md
          - AWX新增容器组: 运维开发/AWX/AWX新增容器组.md
          - 在k3s上搭建awx测试环境: 运维开发/AWX/在k3s上搭建awx测试环境.md
      - Keycloak:
          - 使用openresty容器为k8s的服务提供Keycloak认证服务: 运维开发/Keycloak/使用openresty容器为k8s的服务提供Keycloak认证服务.md
          - k8s集群Keycloak部署及负载配置: 运维开发/Keycloak/k8s集群Keycloak部署及负载配置.md
          - 使用docker-compose搭建keycloak开发环境: 运维开发/Keycloak/使用docker-compose搭建keycloak开发环境.md
      - 笔记及文档软件:
          - 思源笔记k8s部署: 运维开发/笔记及文档软件/思源笔记k8s部署.md
          - mkdocs在k8s上的部署: 运维开发/笔记及文档软件/mkdocs在k8s上的部署.md
          - 编译OnlyOffice以解除20连接数限制: 运维开发/笔记及文档软件/编译OnlyOffice以解除20连接数限制.md
      - Git使用:
          - Git中文乱码问题解决: 运维开发/Git使用/Git中文乱码问题解决.md
          - 最简Git服务器搭建.md: 运维开发/Git使用/最简Git服务器搭建.md
          - GitHub默认头像获取: 运维开发/Git使用/GitHub默认头像获取.md
          - Git配置记住密码: 运维开发/Git使用/Git配置记住密码.md
          - 使用nginx快速搭建只读Git仓库: 运维开发/Git使用/使用nginx快速搭建只读Git仓库.md
          - GitLab第二邮箱修改为已认证: 运维开发/Git使用/GitLab第二邮箱修改为已认证.md
      - Python:
          - 构建解压即用的Python3: 运维开发/Python/构建解压即用的Python3.md
          - 基于Python的模块化监控工具的开发: 运维开发/Python/基于Python的模块化监控工具的开发.md
          - Python升级所有依赖: 运维开发/Python/Python升级所有依赖.md
          - Python限制内存和CPU使用: 运维开发/Python/Python限制内存和CPU使用.md
      - Java:
          - SpringBoot 2.5.1 对接Keycloak认证: 运维开发/Java/SpringBoot 2.5.1 对接Keycloak认证.md
          - 使用OnlyOffice官方Spring示例遇到的坑: 运维开发/Java/使用OnlyOffice官方Spring示例遇到的坑.md
      - Shell:
          - Shell设置变量未赋值或遇到错误立刻退出: 运维开发/Shell/Shell设置变量未赋值或遇到错误立刻退出.md
      - Rust:
          - Rust离线开发环境安装: 运维开发/Rust/Rust离线开发环境安装.md
          - Rust交叉编译环境安装: 运维开发/Rust/Rust交叉编译环境安装.md
  - 折腾Linux:
      - 通用Linux:
          - Linux下载yum源: 折腾Linux/通用Linux/Linux下载yum源.md
          - Linux挂载CIFS: 折腾Linux/通用Linux/Linux挂载CIFS.md
          - Linux LVM踢PV: 折腾Linux/通用Linux/Linux LVM踢PV.md
          - Linux将最后一个磁盘分区扩容到最大: 折腾Linux/通用Linux/Linux将最后一个磁盘分区扩容到最大.md
          - Linux配置udev规则忽略磁盘: 折腾Linux/通用Linux/Linux配置udev规则忽略磁盘.md
          - 使用tlog对登录到Linux上的用户进行录屏: 折腾Linux/通用Linux/使用tlog对登录到Linux上的用户进行录屏.md
          - Kickstart 软raid安装.md: 折腾Linux/通用Linux/Kickstart 软raid安装.md
      - Gentoo:
          - 在QEMU环境安装Gentoo: 折腾Linux/Gentoo/在QEMU环境安装Gentoo.md
          - 在Hyper-V环境安装Gentoo: 折腾Linux/Gentoo/在Hyper-V环境安装Gentoo.md
          - emerge装包ninja报错“manifest 'build.ninja' still dirty after 100 tries”解决方法: 折腾Linux/Gentoo/emerge装包ninja报错“manifest 'build.ninja' still dirty after 100 tries”解决方法.md
          - Gentoo启动时挂载cifs失败解决方法: 折腾Linux/Gentoo/Gentoo启动时挂载cifs失败解决方法.md
          - Hyper-V环境下sddm无法启动图形界面问题解决: 折腾Linux/Gentoo/Hyper-V环境下sddm无法启动图形界面问题解决.md
          - 安装xfce后fcitx右上角显示但无法选择输入法问题解决: 折腾Linux/Gentoo/安装xfce后fcitx右上角显示但无法选择输入法问题解决.md
      - OpenWrt:
          - OpenWrt安装WireGuard: 折腾Linux/OpenWrt/OpenWrt安装WireGuard.md
          - OpenWrt安装OpenVPN: 折腾Linux/OpenWrt/OpenWrt安装OpenVPN.md
          - OpenWrt DDNS开机启动失败问题: 折腾Linux/OpenWrt/OpenWrt DDNS开机启动失败问题.md
          - 小米AX9000解锁SSH: 折腾Linux/OpenWrt/小米AX9000解锁SSH.md
          - 小米AX9000刷机: 折腾Linux/OpenWrt/小米AX9000刷机.md
          - 小米AX9000加入160MHz支持: 折腾Linux/OpenWrt/小米AX9000加入160MHz支持.md
          - 北京联通中兴F4610U光猫开超管界面: 折腾Linux/OpenWrt/北京联通中兴F4610U光猫开超管界面.md
          - OpenWrt修改默认Shell为bash并开启历史命令时间戳: 折腾Linux/OpenWrt/OpenWrt修改默认Shell为bash并开启历史命令时间戳.md
      - Ubuntu:
          - Ubuntu安装Hyper-V工具: 折腾Linux/Ubuntu/Ubuntu安装Hyper-V工具.md
      - RHEL6:
          - 记某次误操作yum update后jboss应用无法启动及重启无法识别vg问题: 折腾Linux/RHEL6/记某次误操作yum update后jboss应用无法启动及重启无法识别vg问题.md
      - 中标麒麟V7:
          - 曙光服务器装机无RAID卡驱动导致不能识别硬盘问题分析与解决方案: 折腾Linux/中标麒麟V7/曙光服务器装机无RAID卡驱动导致不能识别硬盘问题分析与解决方案.md
          - 联想物理机PXE装机报错“根分区找不到”原因及解决方法: 折腾Linux/中标麒麟V7/联想物理机PXE装机报错“根分区找不到”原因及解决方法.md
      - 银河麒麟V10:
          - 记某次某安全厂商应用运行一段时间后Linux出现ping延迟高问题的解决思路: 折腾Linux/银河麒麟V10/记某次某安全厂商应用运行一段时间后，Linux出现ping延迟高问题的解决思路.md
  - 虚拟化技术:
      - Hyper-V:
          - Hyper-V修改调度器: 虚拟化技术/Hyper-V/Hyper-V修改调度器.md
          - Hyper-V网卡直通: 虚拟化技术/Hyper-V/Hyper-V网卡直通.md
      - QEMU:
          - virt-manager创建虚拟机报错“Did not find any UEFI binary path for arch 'aarch64'”问题: ./虚拟化技术/QEMU/virt-manager创建虚拟机报错“Did not find any UEFI binary path for arch 'aarch64'”问题.md
      - 华为云:
          - 华为HCS 8与银河麒麟V10SP4 cloud-init适配问题解决: 虚拟化技术/华为云/华为HCS 8与银河麒麟V10SP4 cloud-init适配问题解决.md
  - 文档分类: tags.md
plugins:
  - search: null
  - open-in-new-tab: null
  - privacy: null
  - offline: null
  - git-revision-date-localized:
      enable_creation_date: true
      locale: zh
  - tags:
      tags_file: tags.md
  - add-number:
      strict_mode: False
      order: 2
      excludes:
        - tags.md
  - print-site: null
markdown_extensions:
  - attr_list: null
  - abbr: null
  - admonition: null
  - pymdownx.caret: null
  - pymdownx.critic: null
  - pymdownx.details: null
  - pymdownx.extra: null
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      linenums: true
  - pymdownx.inlinehilite: null
  - pymdownx.keys: null
  - pymdownx.mark: null
  - pymdownx.magiclink: null
  - pymdownx.progressbar: null
  - pymdownx.smartsymbols: null
  - pymdownx.snippets: null
  - pymdownx.superfences: null
  - pymdownx.tilde: null
  - pymdownx.tasklist: null
  - pymdownx.tabbed: null
  - toc:
      permalink: true
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - mdx_truly_sane_lists
